apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.agent.globalScrapeInterval }}
      scrape_timeout: {{ .Values.agent.globalScrapeTimeout }}
      evaluation_interval: {{ .Values.agent.evaluationInterval }}

    remote_write:
      {{- range .Values.agent.remotes }}
      - url: {{ .url }}
        basic_auth:
          username: {{ .Values.agent.remotes.basic.username }}
          password: {{.Values.agent.remotes.basic.password }}
      {{- end }}

    scrape_configs:
      {{- toYaml .Values.agent.scrape | nindent 6 }}
