apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.agent.interval }}
      scrape_timeout: {{ .Values.agent.timeout }}
      evaluation_interval: {{ .Values.agent.evaluation }}

    remote_write:
      {{- range .Values.agent.remotes }}
      - url: {{ .url }}
        {{- if .basic }}
        basic_auth:
          username: {{ .basic.username }}
          password: {{ .basic.password }}
        {{ end }}
      {{- end }}

    scrape_configs:
      {{- toYaml .Values.agent.scrape | nindent 6 }}
