{{- if .Values.autoscale.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "prometheus-agent.fullname" . }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscale.targetCPUUtilizationPercentage }}
{{- end }}
