{{- if .Values.budget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.budget.minAvailable }}
  selector:
    matchLabels:
      {{- include "prometheus-agent.selectorLabels" . | nindent 6 }}
{{- end }}
