{{- if .Values.account.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
  {{- with .Values.account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
