apiVersion: v2
name: agent
description: 使用Agent模式的图纸
type: application
version: 0.0.8
appVersion: "v3.4.1"
keywords:
  - prometheus
  - monitoring
  - metrics
  - agent
home: https://prometheus.io
sources:
  - https://github.com/prometheus/prometheus
maintainers:
  - name: storezhang
    email: storezhang@qq.com