apiVersion: v2
name: prometheus-agent
description: A Helm chart for deploying Prometheus in Agent mode (--enable-feature=agent)
type: application
version: 0.0.1
appVersion: "v3.4.1"
keywords:
  - prometheus
  - monitoring
  - metrics
  - agent
home: https://prometheus.io
sources:
  - https://github.com/prometheus/prometheus
maintainers:
  - name: platform-team
    email: platform@example.com